apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces
  - network-policies
  - postgres
  - redis
  - infisical
  - cert-manager
  - cloudflared
  - traefik
  - observability
  - backup
